name: Analyze repository

# Run for main or PRs against main
on:
  push:
    branches: [ "main" ]
  
  workflow_dispatch:

jobs:
  analyze:
    name: Analyze repository
    runs-on: ubuntu-latest    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Run PSRule analysis
      uses: microsoft/ps-rule@v2.7.0
      with:
        modules: PSRule.Rules.Azure
        path: IaC_with_ARM_and_Bicep/templates
