on: [push]
name: Azure Resource Manager - Resource Group Deploy
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: ARM Template Toolkit (ARM TTK)
      uses: aliencube/arm-ttk-actions@v0.3
      with:
       path: ./IaC_with_ARM_and_Bicep/templates/ResourceGroup/

    # Checkout code
    - name: Checkout Code
      uses: actions/checkout@main

    # Log into Azure
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CONNECTION }}
      
    - name: DeployARM        
      id: DeployARM
      uses: Azure/arm-deploy@v1
      with:
        scope: subscription
        region: eastus
        deploymentName: GitHub_Deploy_ResourceGroup          
        template: IaC_with_ARM_and_Bicep/templates/ResourceGroup/resource_group.json
        parameters: IaC_with_ARM_and_Bicep/templates/ResourceGroup/resource_group.parameters.json          
          
    # output containerName variable from template  
    # - name: Write Output
    # - run: echo 'Resource Group Name:' ${{ steps.deployARM.outputs.ResourceGroupName }}
    # - run: echo 'Resource Group Location:' ${{ steps.deployARM.outputs.ResourceGroupLocation }}
