on: [push]
name: Azure Resource Manager - Resource Group Deploy
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # Checkout code
      - uses: actions/checkout@main

    # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CONNECTION }}
      
      - name: DeployARM        
        id: DeployARM
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription          
          deploymentName: GitHub_Deploy_ResourceGroup          
          template: IaC_with_ARM_and_Bicep/templates/ResourceGroup/resource_group.json
          parameters: IaC_with_ARM_and_Bicep/templates/ResourceGroup/resource_group.parameters.json
          deploymentOutputs: 'ResourceGroupName'
          
    # output containerName variable from template
      - run: echo ${{ steps.deployARM.outputs.ResourceGroupName }}
      - run: echo ${{ steps.deployARM.outputs.* }}
      - run: echo $(ResourceGroupName)
