name: Validate Resource Group Template

on:
  workflow_dispatch:

jobs:
  ValidateTemplate_ResourceGroup:    
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          ref: main
        
      - name: Validate ARM Template
        uses: microsoft/action-armttk@0.0.5
        with:         
          github_token: ${{ secrets.GITHUB_TOKEN }}          
          workdir: IaC_with_ARM_and_Bicep/templates/ResourceGroup/
          glob_pattern: "**/*.json"
          tool_name: armttk
          level: error
          reporter: github-pr-check
          filter_mode: added
          fail_on_error: true
          reviewdog_flags: bug
      
      - name: Create issue about failure
        if: failure()
        uses: JasonEtco/create-an-issue@v2.9.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          update_existing: true
          assignees: ${{ GITHUB.ACTOR }}
          filename: IaC_with_ARM_and_Bicep/templates/action-issue-template.md

      - name: Close Issue (if tests pass)
        if: success()
        uses: actions/stale@v3
        with:
          only-labels: 'arm-ttk-failure'
          stale-issue-label: 'resolved'
          stale-issue-message: 'All tests passes. Issue is resolved'
          close-issue-message: 'Closing issue.'
          days-before-issue-stale: 0
          days-before-close: 0
