name: Validate Resource Group Template

on:
  workflow_dispatch:

jobs:
  ValidateTemplate_ResourceGroup:    
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          ref: main
        
      - name: Validate ARM Template
        uses: microsoft/action-armttk@0.0.5
        with:         
          github_token: ${{ secrets.GITHUB_TOKEN }}          
          workdir: IaC_with_ARM_and_Bicep/templates/ResourceGroup/
          glob_pattern: "**/*.json"
          tool_name: armttk
          level: error
          reporter: github-pr-check
          filter_mode: added
          fail_on_error: true
          reviewdog_flags: bug
      
      - name: open-issue
        if: failure()
        uses: rishabhgupta/git-action-issue@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ env.GITHUB_WORKFLOW }} - GitHub Action is failing...
          body: The ARM Template {{ env.GITHUB_WORKFLOW }} failed. Please see more details above and fix the issues before pull request
                |           Name             |                  Value                  |
                | -------------------------- | --------------------------------------- |
                | Start Trigger Type         | {{ env.GITHUB_EVENT_NAME }}             |
                | Branch Code                | {{ env.GITHUB_REF_NAME }}               |
                | Code Repository            | {{ env.GITHUB_REPOSITORY }}             |
                | GitHub Action Job          | {{ env.GITHUB_JOB }}                    |
                | GitHub Action Started by   | {{ env.GITHUB_ACTOR }}                  |
                | Execution Attempts         | {{ env.GITHUB_RUN_ATTEMPT }}            | 
                | Agent Type                 | {{ env.RUNNER_NAME }}                   |
                | Agent OS                   | {{ env.RUNNER_OS }}                     |
                | OS Architecture            | {{ env.RUNNER_ARCH }}                   |
                | Log Retention in Days      | {{ env.GITHUB_RETENTION_DAYS }}         |

            >**Note**
            > See {{ env.GITHUB_SERVER_URL }}/{{ env.GITHUB_REPOSITORY }}/actions/runs/{{ env.GITHUB_RUN_ID }} for more information.
          assignees: ${{ env.GITHUB_ACTOR }}
